### PR TITLE
Allow stdlib v8

### PR DESCRIPTION
**Pull request by sazzle2611**

### CODE REVIEW

**Comment by bodgit** [comment]
Can you update the `.fixtures.yml` to use the latest 8.x stdlib release as well? Other than that, looks fine to me.

**Comment by sazzle2611** [comment]
Thank you, sorry I missed that one, only did my first PR last night so still have lot to learn!!

**Comment by bodgit** [comment]
I've just pushed v3.1.2 to the Forge.

**Comment by sazzle2611** [comment]
Great, thank you so much :)

**Pull request merged**
