### PR TITLE
Add `mydomain_fallback` parameter

### PR DESCRIPTION
**Pull request by trevharmon**
The `mydomain_fallback` parameter seems to be missing for the `main.cf` file.

### CODE REVIEW

**Comment by bodgit** [comment]
Hmm, what platform and version of Postfix is that? I can't see `mydomain_fallback` mentioned on http://www.postfix.org/postconf.5.html which makes me suspect it's been added by a vendor for a specific platform.

**Comment by trevharmon** [comment]
I'm seeing this on OEL 6.6 64-bit for Postfix 2.6.6-6.

**Comment by bodgit** [comment]
If I search for `postfix mydomain_fallback` I can only find references to running Postfix on OS X and even then it's often only mentioned as something like `postconf: warning: /etc/postfix/main.cf: unused parameter: mydomain_fallback=localhost` which makes me suspect it's not a valid parameter. I've checked the Postfix configuration on my Mac and it doesn't mention it anywhere. I also pulled down the OEL RPM for the version you have and it's not mentioned in there.

What *is* valid on Postfix is to define a variable (such as `mydomain_fallback`) and then use it as the value for another valid parameter, for example `some_parameter = ${mydomain_fallback}`. If I add the following to my `main.cf`:

```
mydomain_fallback = localhost
mydomain = ${mydomain_fallback}
```

Then `postconf -n` shows the two parameters but if I leave out the second line then Postfix warns that `mydomain_fallback` is unused, i.e. it's just a variable assignment and not a real parameter.

If you could supply your `main.cf` that might explain it. You can also use the `postfix::main` defined type to add such variables but I couldn't add them as class parameters as I'd have to add everybody's variable names.

**Comment by trevharmon** [comment]
We've determined this particular item is an artifact from an old configuration file. Thank you.

**Comment by bodgit** [comment]
Cool, glad you found it. The output of `postconf -d` should probably be the authoritative source when adding new parameters. I'll add something to that affect to the README.

**Pull request closed without merging**
